In [2]:
import numpy as np

## DataTypes and Attributes

In [5]:
#numpy main datatype is ndarray (where n denoted to any 
# number and d to dimentions)

# 1-d array
a1 = np.array([1,2,3,4,6])
a1

array([1, 2, 3, 4, 6])

In [6]:
# size = denotes the number of elements
# shape = denoted the rows,column, etc
# for 1-d shape is the number of elements in it
a1.size , a1.shape

(5, (5,))

In [7]:
# 2-d array = matrix
a2 = np.array([[1,2,3],
               [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# shape = (row , column) = ( 2, 3 )
# size  = row * column = no of elements = 6
a2.size , a2.shape

(6, (2, 3))

In [14]:
# n-d array = multidimensional arrays
a3 = np.array([
               [[1,2,3],
                [4,5,6]],
              
               [[4,5,6],
               [1,2,3]],
              
              [[4,5,6],
               [1,2,3]],
    
              [[4,5,6],
               [1,2,3]]  ])
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [1, 2, 3]],

       [[4, 5, 6],
        [1, 2, 3]],

       [[4, 5, 6],
        [1, 2, 3]]])

In [15]:
# a3 is the multidimentional array
# shape = the end two number will be row and column ( 4,2,3) and the first
# denoting the sets
a3.shape , a3.size


((4, 2, 3), 24)

In [17]:
# this is how to check the dimention of the array
# a3  is 3 dimention as . it's have row(h)  , colmn(w)  and set(l)
a1.ndim , a3.ndim , a2.ndim

(1, 3, 2)

In [18]:
# it's datatype 
type(a1) , type(a2) , type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [26]:
 # numpy in panda
import pandas as pd
p1 = pd.DataFrame({"num" : a1})
p1

num
0    1
1    2
2    3
3    4
4    6

In [29]:
p2 = pd.DataFrame(a2)
p2

0  1  2
0  1  2  3
1  4  5  6

## Creating Arrays

In [33]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
ones = np.ones((4,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
ones.dtype , zeros.dtype

(dtype('float64'), dtype('float64'))

#### there are many other functions
##### arange 
##### randint
##### random


In [8]:
# arange = interval value fron start and end
np.arange(-20,0,3)

array([-20, -17, -14, -11,  -8,  -5,  -2])

In [25]:
# randint = in int, random numbers (with given start and end)
randomint = np.random.randint(0,10, size=(2,5,3))
randomint

array([[[6, 9, 3],
        [7, 7, 4],
        [5, 9, 3],
        [6, 8, 0],
        [2, 7, 7]],

       [[9, 7, 3],
        [0, 8, 7],
        [7, 1, 1],
        [3, 0, 8],
        [6, 4, 5]]])

In [24]:
randomint.size , randomint.shape

(30, (2, 5, 3))

In [46]:
#random = in float , random number between 0 and 1
randomfloat = np.random.random((5,3))
randomfloat

array([[0.31733098, 0.05286529, 0.28243944],
       [0.90087516, 0.82283217, 0.98596003],
       [0.43790585, 0.64738517, 0.6573452 ],
       [0.75787086, 0.31262411, 0.5122502 ],
       [0.69339823, 0.80743113, 0.71473099]])

### seed()

In [31]:
#seed = maintain the random array state , by setting the seed number
np.random.seed(1)
randomint

array([[[6, 9, 3],
        [7, 7, 4],
        [5, 9, 3],
        [6, 8, 0],
        [2, 7, 7]],

       [[9, 7, 3],
        [0, 8, 7],
        [7, 1, 1],
        [3, 0, 8],
        [6, 4, 5]]])

In [49]:
np.random.seed(99999)
randomfloat

array([[0.31733098, 0.05286529, 0.28243944],
       [0.90087516, 0.82283217, 0.98596003],
       [0.43790585, 0.64738517, 0.6573452 ],
       [0.75787086, 0.31262411, 0.5122502 ],
       [0.69339823, 0.80743113, 0.71473099]])

In [60]:
np.random.seed(4)
random1 = np.random.randint(0,10,size=(2,4))
random1

array([[7, 5, 1, 8],
       [7, 8, 2, 9]])

In [58]:
random1 = np.random.randint(0,10,size=(2,4))
random1

array([[6, 8, 2, 5],
       [8, 1, 2, 7]])

## Viewing arrays and matrices

In [3]:
a1 = np.random.randint(0,10,size=(2,3))
a1

array([[6, 6, 0],
       [1, 0, 5]])

In [17]:
#access the colmn
#access the row

a1[:,2], a1[1]

(array([0, 5]), array([1, 0, 5]))

In [19]:
#access on element 
a1[1][2]

5

In [20]:
a = np.array([1,2,3,4])
a[3]

4

## Manipulating and comparing arrays

### Arithmetic

In [39]:
a1 = np.array([1,2,3,4])
a1 

array([1, 2, 3, 4])

In [29]:
a2 = np.array([5,6,7,8])
a2

array([5, 6, 7, 8])

In [31]:
a1 + a2 , a1- a2 , a1 * a2

(array([ 6,  8, 10, 12]), array([-4, -4, -4, -4]), array([ 5, 12, 21, 32]))

In [41]:
a3 = np.random.randint(0,9, size = (2,4))
a3

array([[3, 4, 1, 4],
       [8, 1, 7, 7]])

In [44]:
a1

array([1, 2, 3, 4])

In [47]:
a1 * a3 , a1 + a3 , a3 - a1

(array([[ 3,  8,  3, 16],
        [ 8,  2, 21, 28]]),
 array([[ 4,  6,  4,  8],
        [ 9,  3, 10, 11]]),
 array([[ 2,  2, -2,  0],
        [ 7, -1,  4,  3]]))

In [48]:
# for more knowlege and problem = learn broadcasting rules
# Broadcasting = The term broadcasting describes how NumPy treats
#                arrays with different shapes during arithmetic operations.


In [56]:
a2 , a1

(array([5, 6, 7, 8]), array([1, 2, 3, 4]))

In [55]:
# / = provide the quotient
# // = provide the remainder
a1/a2  , a1//a2

(array([0.2       , 0.33333333, 0.42857143, 0.5       ]), array([0, 0, 0, 0]))

In [58]:
np.sqrt(a2) , np.square(a2) , a1 ** 3

(array([2.23606798, 2.44948974, 2.64575131, 2.82842712]),
 array([25, 36, 49, 64]),
 array([ 1,  8, 27, 64], dtype=int32))

## Aggregation

In [ ]:
# aggregation defination = Aggregation in NumPy means combining multiple values in an array 
#                          to compute a single summary value, such as finding the sum, mean, maximum,
#                          or minimum of the array's elements.

In [59]:
# python list
pythonlist = [1,2,3]
pythonlist

[1, 2, 3]

In [60]:
# numpy array
numpyarray = np.array([4,5,6])
numpyarray

array([4, 5, 6])

In [61]:
# summing up python with python sum() function
# and numpy with np.sum() function
sum(pythonlist) , np.sum(numpyarray)

(6, 15)

Recommendation = Use python's method (sum()) on python datatypes and use numPy's methods (np.sum()) on arrays


numpy is almost 5 times faster than the python operations

In [11]:
massivedb = np.random.random(size=(200000))
massivedb[:10]


array([0.17497545, 0.26984502, 0.86396504, 0.60044907, 0.11379072,
       0.95066527, 0.14052781, 0.35778624, 0.20645321, 0.82605442])

In [10]:
 %timeit sum(massivedb) 
 %timeit np.sum(massivedb)

37.6 ms ± 2.14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
201 µs ± 2.85 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [12]:
np.mean(massivedb) , np.min(massivedb) , np.max(massivedb)

(0.49896684406254754, 7.1258305189836335e-06, 0.9999978939328417)

### Reshaping and transposing

In [3]:
# till now , what i have learned is that reshaping and transposing is used to avoid 
# the broadcasting error (error comes in arithmetic of two datatypes)

In [6]:
z= np.random.randint(0,10,size=(2,3))
z

array([[6, 7, 1],
       [8, 0, 6]])

In [7]:
z.T

array([[6, 8],
       [7, 0],
       [1, 6]])

##### how tansposing helped


##### Dot product

In [10]:
# dot product rule = (2,3) (3,4)
#                    (5,4) (4,6)
# dot product occur , when the inner element is have similar value
# dot product = work exactly as did in 12th std , multipy two matrix
z , z.shape

(array([[6, 7, 1],
        [8, 0, 6]]),
 (2, 3))

In [11]:
y = np.random.randint(0,10,size=(4,3))

array([[0, 7, 7],
       [0, 8, 3],
       [3, 9, 0],
       [2, 2, 6]])

In [13]:
# error in dot product, as condition not met
z.shape , y.shape

((2, 3), (4, 3))

In [17]:
# transporting the y matrix for fullfiling the conditions
y.T.shape 

(3, 4)

In [20]:
np.dot(z,y)

ValueError: shapes (2,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [19]:
np.dot(z,y.T)

array([[56, 59, 81, 32],
       [42, 18, 24, 52]])

#### Standard deviation and variance are measures of "spread" of Data

The higher standard deviation and the variance , the more spread out the values are

In [22]:
# Standard deviation (std) = a measure of how spread out a group of numbers is from the mean
# Variance (var) = measure of the average degree to which each number is different.

# Higher variance = wider range of numbers
# lower variance  = lower range of numbers

In [23]:
higer_spread = np.array([1,10,100,2000,3000,80000])
lower_spread = np.array([1,3,5,7,9])

In [24]:
# variance
np.var(higer_spread) , np.var(lower_spread)

(867616063.472222, 8.0)

In [26]:
# standard - spread from mean
np.std(higer_spread),np.std(lower_spread)

(29455.323177181777, 2.8284271247461903)


## Dot product practical expercise : karan fav good sales

In [23]:
np.random.seed(0)
sales_data_mat = np.random.randint(1,100,size=(5,3))
sales_data_mat

array([[45, 48, 65],
       [68, 68, 10],
       [84, 22, 37],
       [88, 71, 89],
       [89, 13, 59]])

In [24]:
## converting it into gud form , datafram
import pandas as pd
sales_data = pd.DataFrame(sales_data_mat, index= ["Mon","Tues","wed","Thurs","Fri"], 
                          columns = ["rajma-rice","thumbs-up","malai-chiken pizza"])
sales_data

rajma-rice  thumbs-up  malai-chiken pizza
Mon            45         48                  65
Tues           68         68                  10
wed            84         22                  37
Thurs          88         71                  89
Fri            89         13                  59

In [25]:
price_chart_mat = np.array([250,80 , 300])
price_chart_mat.reshape(1,3).shape

(1, 3)

In [27]:
price_chart = pd.DataFrame(price_chart_mat.reshape(1,3),index=["prices of items"], columns=["rajma-rice","thumbs-up","malai-chiken pizza"])
price_chart

rajma-rice  thumbs-up  malai-chiken pizza
prices of items         250         80                 300

In [28]:
price_chart.shape , sales_data.T.shape

((1, 3), (3, 5))

In [29]:
total_price_mat = price_chart_mat.dot(sales_data_mat.T)
total_price_mat

array([34590, 25440, 33860, 54380, 40990])

In [33]:
total_price = pd.DataFrame(total_price_mat,index= ["Mon","Tues","wed","Thurs","Fri"], 
                          columns = ["total sale of each item (INR)"])
total_price

total sale of each item (INR)
Mon                            34590
Tues                           25440
wed                            33860
Thurs                          54380
Fri                            40990

In [34]:
sales_data

rajma-rice  thumbs-up  malai-chiken pizza
Mon            45         48                  65
Tues           68         68                  10
wed            84         22                  37
Thurs          88         71                  89
Fri            89         13                  59

In [37]:
sales_data["total sale of each item (INR)"] = total_price
sales_data

rajma-rice  thumbs-up  malai-chiken pizza  \
Mon            45         48                  65   
Tues           68         68                  10   
wed            84         22                  37   
Thurs          88         71                  89   
Fri            89         13                  59   

       total sale of each item (INR)  
Mon                            34590  
Tues                           25440  
wed                            33860  
Thurs                          54380  
Fri                            40990

In [38]:
price_chart

rajma-rice  thumbs-up  malai-chiken pizza
prices of items         250         80                 300