In [1]:
 import numpy as np

In [5]:
oneD_array = np.array([1,2,3])
oneD_array.shape

(3,)

In [4]:
twoD_array = np.array([[1,2,3],
                     [4,5,6]])
twoD_array.shape

(2, 3)

In [7]:
threeD_array = np.array([[[1,2,3],
                        [1,2,3]],
                         
                        [[1,2,3],
                        [1,2,3]]])
threeD_array.shape

(2, 2, 3)

In [8]:
oneD_array.shape, twoD_array.shape,threeD_array.shape

((3,), (2, 3), (2, 2, 3))

In [10]:
oneD_array.dtype, twoD_array.dtype,threeD_array.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [13]:
oneD_array.size , twoD_array.size , threeD_array.size

(3, 6, 12)

In [17]:
import pandas as pd
oneD_array_panda = pd.DataFrame(oneD_array, index=["one","two","three"],columns=["size"])
oneD_array_panda

size
one       1
two       2
three     3

In [18]:
one  = np.ones(shape=(10,2))
one

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
zeros = np.zeros(shape=(7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
random = np.random.randint(0,10,size=(7,2))
random

array([[8, 2],
       [6, 5],
       [5, 5],
       [9, 7],
       [9, 3],
       [3, 4],
       [6, 9]])

AttributeError: module 'numpy.random' has no attribute 'randfloat'